### ISSUE TITLE
Add linter rules/enable Detekt linter rules

### ISSUE THREAD

**Issue by LeoColman** [boguszpawlowski/ComposeCalendar#55]
# Context

In pull request #44 we have a lot of small comments about formatting/lint-solvable issues.

I understand that Detekt is the tool for this, but is it being enforced in any way? It seems to me that it should catch those mistakes.

## Extra information

https://medium.com/@aayushsharda/why-is-it-better-to-avoid-in-import-statements-in-java-ff9ceaca8aeb

**Comment by boguszpawlowski** [comment]
@LeoColman The Detekt is a blocking check on the PR. The comments from the #44 that you mention are on the old version of the diff, that's why the check is green now ;) I will close this issue, but if you have an idea on improving this check and/or want to contribute to it, please feel free to do such.
