### ISSUE TITLE
Update accompanist

### ISSUE THREAD

**Issue by gl00k** [boguszpawlowski/ComposeCalendar#73]
Hi guys
thank you for a wonderful library

but i have a problem
when I use accompanist above version 0.23.1 (pager) in my project, your calendar crashes

update accompanist please

**Comment by ArnyminerZ** [comment]
Updating should be available, but since 0.23.1+ versions are marked as "alpha", "beta", or "rc" the automatic dependency updater doesn't run and it gets stuck with 0.23.1. I'm also not able to use the library because of this, so I hope Google releases an stable version of Accompanist Pager, or @boguszpawlowski changes something to fix this 😞

**Comment by ArnyminerZ** [comment]
You can import the whole source of the project into yours, and it shall work. However, take into account that the project uses min SDK version of 26, so if you are using a lower value I recommend you to update, or find another one, since you practically have to rewrite the whole code.

**Comment by boguszpawlowski** [comment]
@gl00k @ArnyminerZ The accompanist 0.24 is based on Compose 1.2, which wasn't released yet. Once it will be released, I can update the ComposeCalendar dependencies as well.

**Comment by renanboni** [comment]
@boguszpawlowski hey, jetpack compose 2.0 has been released 😄

**Comment by boguszpawlowski** [comment]
@renanboni Thanks for the heads-up, released 0.6.0 version with Compose 1.2.0 and accompanist 0.25.0
