### ISSUE TITLE
API to provide a week overlap

### ISSUE THREAD

**Issue by YuraLaguta** [boguszpawlowski/ComposeCalendar#80]
First of all thank you for open-sourcing such a great library. 

I'm playing with a way to build something similar to google calendar where events can be shown for ranges of days, thinking of adding API for providing a week overlapping composable.

Is it something you would be open to merge into this library?

**Comment by boguszpawlowski** [comment]
Hi @YuraLaguta! Thanks for creating such issue. Do you have a particular idea how such feature would work (from the code side of things, not design).

**Comment by boguszpawlowski** [comment]
Ok, I got the idea, thanks! I'm just wondering  if it wouldn't  be possible to implement it using existing API? You would just have to do this on the DayContent level. I'm not saying it is better, just wondering if it will not confuse the user more if we do it this way.  Overall, I think there is room for such a feature. I would just propose to find a way to provide an easier API (e.g. based on providing a range of days), to simplify adding such views instead of providing multiple ways to do so. 
<img width="1270" alt="Screenshot 2022-10-26 at 20 38 37" src="https://user-images.githubusercontent.com/36514058/198108889-7f446fc2-39b7-40d7-abcc-103e63e49556.png">

**Comment by boguszpawlowski** [comment]
@YuraLaguta Closing this issue as there were no updates for over half a year, feel free to reopen it.
