### ISSUE TITLE
How to hold a DaysState or MonthState before it changes?

### ISSUE THREAD

**Issue by NebilHassen** [boguszpawlowski/ComposeCalendar#99]
Im having a hard time getting a hold of the state change of the monthState or daysState ( using it to trigger a API call, the issue has been raised in issue 84, but the solution does not seem to fit, the state changes before launched effect comes into effect )

**Comment by boguszpawlowski** [comment]
Hmm, If you want to execute re-fetch the data BEFORE the state change, I suppose this would require a change in library, some sort of callback before state change, similar to the one for selection state. 
However, I'm not so convinced about it, normally, I would expect that data is fetched AFTER UI changes, otherwise we might run into sync issues. 
What if the user cancels the swipe, or immediately goes to the previous page? It would mean unnecessary fetching of data.
I would also say, that pre-fetching the data (e.g. fetching days from +/- 3 days around current day) would greatly reduce the lag.
@NebilHassen Please let me know what you think

**Comment by boguszpawlowski** [comment]
Closing as stale. @NebilHassen Let me know if you want to reopen it.
